/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Edges } from "@react-three/drei";
import modelPath from "../assets/SunCAVE.glb";

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF(modelPath);
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={
					nodes.suncave_complete3dm_suncave_complete3dm_436049
						.geometry
				}
				// material={
				// 	nodes.suncave_complete3dm_suncave_complete3dm_436049
				// 		.material
				// }
				position={[0, 0, 0]}
				rotation={[Math.PI, 0, 0]}
				scale={0.3}
			>
				<meshStandardMaterial
					attach="material"
					transparent={true}
					opacity={0.7}
					color={"#332FD0"}
				/>
				<Edges scale={1} threshold={15} color="#E15FED" />
			</mesh>
		</group>
	);
}

useGLTF.preload(modelPath);
